name: kasirtoko
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  path: ^1.9.1
  solar_icons: ^0.0.5
  sqflite: ^2.4.2
  drops: ^0.0.5
  talker: ^4.6.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_flavorizr: ^2.3.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  freezed: ^3.0.3
  mockito: ^5.4.5
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    # ios:

  flavors:
    admin:
      app:
        name: "Kasko Admin"

      android:
        applicationId: "app.strdy.kaskoadmin"
        icon: "assets/admin-android-icon.png"
      ios:
        bundleId: "app.strdy.kaskoadmin"
        icon: "assets/admin-ios-icon.png"
    user:
      app:
        name: "Kasko"

      android:
        applicationId: "app.strdy.kasko"
        icon: "assets/user-android-icon.png"
      ios:
        bundleId: "app.strdy.kasko"
        icon: "assets/user-ios-icon.png"
